CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE departments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  valid_from DATE NOT NULL,
  valid_to DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE TRIGGER departments_set_updated_at
BEFORE UPDATE ON departments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE positions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  valid_from DATE NOT NULL,
  valid_to DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE TRIGGER positions_set_updated_at
BEFORE UPDATE ON positions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE employees (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  join_date DATE NOT NULL,
  department_id INTEGER NOT NULL REFERENCES departments (id),
  position_id INTEGER NOT NULL REFERENCES positions (id),
  is_full_time BOOLEAN NOT NULL,
  birth_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER employees_set_updated_at
BEFORE UPDATE ON employees
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

INSERT INTO departments (id, name, valid_from, valid_to)
OVERRIDING SYSTEM VALUE
VALUES
  (1, 'Market', DATE '2020-01-01', NULL),
  (2, 'Finance', DATE '2020-01-01', NULL),
  (3, 'Development', DATE '2020-01-01', NULL);

INSERT INTO positions (id, name, valid_from, valid_to)
OVERRIDING SYSTEM VALUE
VALUES
  (1, 'Staff', DATE '2020-01-01', NULL),
  (2, 'Manager', DATE '2020-01-01', NULL),
  (3, 'Director', DATE '2020-01-01', NULL);

INSERT INTO employees (
  id,
  name,
  join_date,
  department_id,
  position_id,
  is_full_time,
  birth_date
)
OVERRIDING SYSTEM VALUE
VALUES
  (
    1,
    'Edward Perry',
    DATE '2025-07-16',
    2,
    2,
    TRUE,
    DATE '2000-03-12'
  ),
  (
    2,
    'Josephine Drake',
    DATE '2025-07-16',
    1,
    1,
    FALSE,
    DATE '1989-11-04'
  ),
  (
    3,
    'Cody Phillips',
    DATE '2025-07-16',
    3,
    1,
    TRUE,
    DATE '2006-08-21'
  );

SELECT setval(
  pg_get_serial_sequence('departments', 'id'),
  (SELECT MAX(id) FROM departments)
);

SELECT setval(
  pg_get_serial_sequence('positions', 'id'),
  (SELECT MAX(id) FROM positions)
);

SELECT setval(
  pg_get_serial_sequence('employees', 'id'),
  (SELECT MAX(id) FROM employees)
);
