CREATE TABLE departments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE positions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE employees (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL CHECK (age > 0),
  join_date TIMESTAMPTZ NOT NULL,
  department_id INTEGER NOT NULL REFERENCES departments (id),
  position_id INTEGER NOT NULL REFERENCES positions (id),
  is_full_time BOOLEAN NOT NULL,
  birth_date TIMESTAMPTZ
);

INSERT INTO departments (id, name)
OVERRIDING SYSTEM VALUE
VALUES
  (1, 'Market'),
  (2, 'Finance'),
  (3, 'Development');

INSERT INTO positions (id, name)
OVERRIDING SYSTEM VALUE
VALUES
  (1, 'Staff'),
  (2, 'Manager'),
  (3, 'Director');

INSERT INTO employees (
  id,
  name,
  age,
  join_date,
  department_id,
  position_id,
  is_full_time,
  birth_date
)
OVERRIDING SYSTEM VALUE
VALUES
  (
    1,
    'Edward Perry',
    25,
    TIMESTAMPTZ '2025-07-16 00:00:00+00',
    2,
    2,
    TRUE,
    TIMESTAMPTZ '2000-03-12 00:00:00+00'
  ),
  (
    2,
    'Josephine Drake',
    36,
    TIMESTAMPTZ '2025-07-16 00:00:00+00',
    1,
    1,
    FALSE,
    TIMESTAMPTZ '1989-11-04 00:00:00+00'
  ),
  (
    3,
    'Cody Phillips',
    19,
    TIMESTAMPTZ '2025-07-16 00:00:00+00',
    3,
    1,
    TRUE,
    TIMESTAMPTZ '2006-08-21 00:00:00+00'
  );

SELECT setval(
  pg_get_serial_sequence('departments', 'id'),
  (SELECT MAX(id) FROM departments)
);

SELECT setval(
  pg_get_serial_sequence('positions', 'id'),
  (SELECT MAX(id) FROM positions)
);

SELECT setval(
  pg_get_serial_sequence('employees', 'id'),
  (SELECT MAX(id) FROM employees)
);
