CREATE TABLE departments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE positions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE employees (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL CHECK (age > 0),
  join_date DATE NOT NULL,
  department_id INTEGER NOT NULL REFERENCES departments (id),
  position_id INTEGER NOT NULL REFERENCES positions (id),
  is_full_time BOOLEAN NOT NULL,
  birth_date DATE
);

INSERT INTO departments (id, name)
OVERRIDING SYSTEM VALUE
VALUES
  (1, 'Market'),
  (2, 'Finance'),
  (3, 'Development');

INSERT INTO positions (id, name)
OVERRIDING SYSTEM VALUE
VALUES
  (1, 'Staff'),
  (2, 'Manager'),
  (3, 'Director');

INSERT INTO employees (
  id,
  name,
  age,
  join_date,
  department_id,
  position_id,
  is_full_time,
  birth_date
)
OVERRIDING SYSTEM VALUE
VALUES
  (
    1,
    'Edward Perry',
    25,
    DATE '2025-07-16',
    2,
    2,
    TRUE,
    DATE '2000-03-12'
  ),
  (
    2,
    'Josephine Drake',
    36,
    DATE '2025-07-16',
    1,
    1,
    FALSE,
    DATE '1989-11-04'
  ),
  (
    3,
    'Cody Phillips',
    19,
    DATE '2025-07-16',
    3,
    1,
    TRUE,
    DATE '2006-08-21'
  );

SELECT setval(
  pg_get_serial_sequence('departments', 'id'),
  (SELECT MAX(id) FROM departments)
);

SELECT setval(
  pg_get_serial_sequence('positions', 'id'),
  (SELECT MAX(id) FROM positions)
);

SELECT setval(
  pg_get_serial_sequence('employees', 'id'),
  (SELECT MAX(id) FROM employees)
);
